### ISSUE TITLE
When options updated, windowed logic with nested divs disappear

### ISSUE THREAD

**Issue by trplfr** [jacobworrel/react-windowed-select#11] opened 2019-08-08 11:18 UTC
Hi!

When I update options from state, windowed logic with nested divs disappear, and remains only react-select.

Also, after unsuccesful search (with no-option message), first option (<ItemWrapper key={0} ... />) set height of noOptionMessage.

Bugs?
Any ideas?

Thanks!

**Comment by jacobworrel** [comment] 2019-08-17 23:17
Hi!

Would you mind providing a [codesandbox](https://codesandbox.io) of each bug please?

Thanks!

**Comment by jacobworrel** [comment] 2019-09-10 02:51
@trplfr Closing this issue since no steps to reproduce or sandbox was provided.

**Closed by jacobworrel** 2019-09-10 02:51 UTC
