### ISSUE TITLE
Label break, when it comes to a long label which needs to go for second line.

### ISSUE THREAD

**Issue by mhtamun** [jacobworrel/react-windowed-select#37] opened 2020-06-15 20:02 UTC
I am facing a issue where we have a long long labels which need to break down to second line where it breaks very ugly. 

Demo: 
![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/10486444/84700663-66dcc400-af75-11ea-9f7f-e427fe433453.gif)

**Comment by jacobworrel** [comment] 2020-06-17 03:52
Duplicate of https://github.com/jacobworrel/react-windowed-select/issues/31

**Closed by jacobworrel** 2020-06-17 03:52 UTC
