### ISSUE TITLE
Version 2.0.3 crashes when using SSR (Server Side Rendering)

### ISSUE THREAD

**Issue by hedshafran** [jacobworrel/react-windowed-select#41] opened 2020-08-03 15:53 UTC
After an update from `2.0.2` to `2.0.3` SSR crashes.

Here is the error log:
```
.../node_modules/react-windowed-select/dist/main.js:1
module.exports=function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=7)}([

ReferenceError: window is not defined
    at Module.<anonymous> (.../a-agent/node_modules/react-windowed-select/dist/main.js:1:63074)
    at n (.../node_modules/react-windowed-select/dist/main.js:1:124)
    at.../node_modules/react-windowed-select/dist/main.js:1:923
    at Object.<anonymous> (.../node_modules/react-windowed-select/dist/main.js:1:932)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (.../node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (.../node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
error Command failed with exit code 1.
```

When using SSR there is no `window` object, please don't use `window` directly so SSR will be supported.
For example:
Change this - `Lt=!(!window.document||!window.document.createElement)` into this - `Lt=!(window && (!window.document||!window.document.createElement))`

In this example if `window` is not defined, it will not try to read `document` from it.

I'll downgrade to `2.0.2` for now, but please fix this :)

Thanks!

**Comment by jacobworrel** [comment] 2020-08-10 16:35
@hedshafran Can you submit a reproducible example? The library is not explicitly using the `window` object anywhere so I'm not sure where this is coming from.

**Comment by hedshafran** [comment] 2020-08-11 08:29
Check the `build` folder - `dist/main.js`, you should see direct usage of the `window` object there..It's not your code

**Comment by jacobworrel** [comment] 2020-08-11 17:17
I think this might be an issue with `react-select`... Might be worth looking at these issues:
- https://github.com/JedWatson/react-select/issues/608
- https://github.com/JedWatson/react-select/issues/3802
- https://github.com/JedWatson/react-select/issues/3994

**Comment by hedshafran** [comment] 2020-08-12 07:02
Yep, JedWatson/react-select#3802 shows exactly the code that crashes.
I hope they fix it soon, because I didn't like the workarounds I saw there.
Thanks!

**Comment by gastrid** [comment] 2020-08-12 16:07
Same here!

**Comment by jacobworrel** [comment] 2021-03-27 22:37
Closing this since JedWatson/react-select#3802 was closed.

**Closed by jacobworrel** 2021-03-27 22:37 UTC
Labels: wontfix
